### ISSUE TITLE
Password database

### ISSUE THREAD

**Issue by FredSWR** [Cocolabs-SAS/cocorico-docker#9]
Hi,

We configure talend to retrieve the Mariadb data but we don't know the password of the database.
This is blocking us in the setting of Talend because we need it.

Can you give us the password please ?

Thanks in advance.

Bye !

**Comment by giorgio654** [comment]
Hello @FredSWR,

The databases parameters are stored in the file `app/config/parameters.yml`.
```
parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: cocorico
    database_user: cocorico
    database_password: cocorico
    mongodb_server: 'mongodb://127.0.0.1:27017'
    mongodb_database_name: cocorico
...
```
And the MySQL initialization is done during the image build.
https://github.com/Cocolabs-SAS/cocorico-docker/blob/master/files/init/database.sql
